apiVersion: v1
kind: Secret
metadata:
  name: ghrc-auth
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <BASE64>

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: <BASE64>
  POSTGRES_PASSWORD: <BASE64>

---

apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  APP_SECRET: <BASE64>
  TELEGRAM_BOT_MAIN_TOKEN: <BASE64>
  TELEGRAM_BOT_CREATOR_TOKEN: <BASE64>
  TELEGRAM_BOT_AGENCY_TOKEN: <BASE64>