apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-redis
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/redis-data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-redis-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-pg
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/pg-data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-pg-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-cdn
spec:
  storageClassName: manual
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/cdn"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-cdn-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi